server:
  port: 8081

spring:
  application:
    name: NETONE-PORTAL

  datasource:
    hikari:
      auto-commit: true
    driver-class-name: org.postgresql.Driver
    password: '9dc81d99156554269a71e1465ceec2a19fcdbf79c25798df592a1377ac6cdc2e'
    url: jdbc:postgresql://ec2-52-21-136-176.compute-1.amazonaws.com:5432/d2v1m2d6nidc8s
    username: vzehxkruhpdqoq
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  file:
    path: logs/
    name: netone_portal.log

