server:
  port: 8088

spring:
  datasource:
    hikari:
      auto-commit: true
    driver-class-name: com.mysql.cj.jdbc.Driver
    password:
    url: jdbc:mysql://localhost:3306/netone
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  file:
    path: logs/
    name: netone_portal.log

