server:
  port: 8080

spring:
  datasource:
    hikari:
      auto-commit: true
    driver-class-name: org.postgresql.Driver
    password: '4e1228bf58d86ed7d72b853a72b95044755f27d5c58c14163612873483ed396c'
    url: jdbc:postgresql://ec2-52-200-215-149.compute-1.amazonaws.com:5432/d7b3mcgrqpumv
    username: xpfxllfloezctw
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false

logging:
  file:
    path: logs/
    name: netone_portal.log

